### ISSUE TITLE
Missing installation guide

### ISSUE THREAD

**Issue by tomikmar** [SolomonShorser-OICR/language-cwl-atom#1]
It would be good to have some info in readme how to install this package in Atom editor.

**Comment by SolomonShorser-OICR** [comment]
Eventually I plan to upload this to atom's main package repository, which will make installation much easier. In the meantime you can clone this repo and then use `apm link` to create a symlink from your atom packages directory to your local copy of this repo.

**Comment by SolomonShorser-OICR** [comment]
README has been updated with installation instructions and link to related syntax theme.
